version: "3"

services:
  web:
    container_name: web
    build: ./crawler
    ports:
      - "5000:5000"
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    environment:
      - FLASK_ENV=development
    volumes:
      - ./crawler:/app

  worker:
    build:
      context: ./crawler
    hostname: worker
    entrypoint: celery
    command: -A celery_app.celery worker --loglevel=info
    volumes:
      - ./crawler:/app
    links:
      - rabbitmq
    depends_on: 
      - rabbitmq
  
  monitor:
    build:
      context: ./crawler
    hostname: monitor
    ports:
      - "5555:5555"
    entrypoint: flower
    command: -A celery_app.celery --broker=amqp://guest:guest@rabbitmq:5672/  --address=0.0.0.0 --port=5555
    volumes:
      - ./crawler:/app
    links: 
      - rabbitmq
    depends_on: 
      - rabbitmq
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    hostname: rabbitmq
    volumes: 
      - ./cache:/var/lib/rabbitmq
    
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes: 
      - ./db:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment: 
      ME_CONFIG_MONGODB_SERVER: "mongodb"
    depends_on: 
      - mongodb
